### ISSUE TITLE
Error when import <ModuleName/ModuleName-Swift.h>

### ISSUE THREAD

**Issue by vincephamgrab** [ob/rules_ios#22]
Hi, thanks for sharing useful custom rules. I'm using `apple_framework` for mixed Objective-C and Swift. It works fine when I use Objective-C classes in my Swift files, using umbrella header imports. 

But when I tried to use Swift class in my Objective-C files the build is failed.

In the Objective-C file, I import the generated Swift header as below (my module name is MixecObjcSwift): 
`#import <MixedObjcSwift/MixedObjcSwift-Swift.h>`

> Error: src/MixedObjcSwift/PrintService.m:9:9: fatal error: 'MixedObjcSwift/MixedObjcSwift-Swift.h' file not found

Could you please assist me this issue? I created a demo of this here: https://github.com/vincephamgrab/demo-mixedobjcswift

**Comment by ob** [comment]
I think we have a bug where swift generated headers are not being properly added to the framework... stay tuned.

**Comment by ob** [comment]
Thanks @vincephamgrab for providing an easy way to repro. I see that we are adding the header file to the framework:

```
$ find -L bazel-out | grep MixedObjcSwift-Swift.h
bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift-Swift.h
bazel-out/darwin-fastbuild/bin/src/MixedObjcSwift-Swift.h
bazel-out/darwin-fastbuild/bin/src/MixedObjcSwift/MixedObjcSwift.framework/Headers/MixedObjcSwift-Swift.h
```
However, we are not adding it to any header map:
```
$ hmap print bazel-out/darwin-fastbuild/bin/src/MixedObjcSwift_public_hmap.hmap | grep Swift
GBPrinterService.h -> src/MixedObjcSwift/GBPrinterService.h
MixedObjcSwift.h -> src/MixedObjcSwift/MixedObjcSwift.h
MixedObjcSwift/GBPrinterService.h -> src/MixedObjcSwift/GBPrinterService.h
MixedObjcSwift/MixedObjcSwift.h -> src/MixedObjcSwift/MixedObjcSwift.h
$ hmap print bazel-out/darwin-fastbuild/bin/src/MixedObjcSwift_private_hmap.hmap | grep Swift
GBPrinterService.h -> src/MixedObjcSwift/GBPrinterService.h
MixedObjcSwift.h -> src/MixedObjcSwift/MixedObjcSwift.h
$ hmap print bazel-out/darwin-fastbuild/bin/src/MixedObjcSwift_private_angled_hmap.hmap | grep Swift
```
I think we need to add another header map just for swift headers... maybe call it `${MODULE_NAME}_swift.hmap`. Although if we want to be able to include it both with double-quotes and angled brackets, we'll probably need two separate header maps just for that swift header.

**Comment by wileykestner** [comment]
Prefacing this with: I have no idea what I'm doing, but I'd love to try to help and use this as an opportunity to learn.

I've made a first attempt at fixing this issue by forking both `rules_ios` as well as this demo project.  I've pointed my demo fork at at my fork of `rules_ios`… if that makes any sense.

Here's my [fork of the demo](https://github.com/wileykestner/demo-mixedobjcswift/tree/point-at-fork), be sure to check out the `point-at-fork` branch.

The changes I made to my fork of `rules_ios` were my best attempt at following Oscar's instructions above.  I tried to add another header map, just for Swift headers.

It appears that the code is doing _something_ because a swift header map is now being generated:

```
$ find -L bazel-out | grep MixedObjcSwift_swift_hmap.hmap
bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift_swift_hmap.hmap
bazel-out/darwin-fastbuild/bin/src/MixedObjcSwift_swift_hmap.hmap
```

And it's contents look _plausibly_ relevant…

```
$ hmap print bazel-out/darwin-fastbuild/bin/src/MixedObjcSwift_swift_hmap.hmap
MixedObjcSwift-Swift.h -> src/MixedObjcSwift-Swift.h
MixedObjcSwift/MixedObjcSwift-Swift.h -> src/MixedObjcSwift-Swift.h
```
but I am still seeing the same build error as the original demo, when compiling the `.m` file the angle bracket import couldn't be resolved.  I also tried changing to a double-quote import statement instead, and that did not seem to resolve the issue.

I'm definitely far past the boundary of my understanding here… can anyone point out where I may have gone amiss or any other directions for exploration?

**Comment by ob** [comment]
@wileykestner I think the problem is that the header is being generated by swift in a different path than then one that's being recorded in the header map. What I see is:

```
% find . -name \*.hmap
./bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift_public_hmap.hmap
./bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift_private_hmap.hmap
./bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift_private_angled_hmap.hmap
./bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift_swift_hmap.hmap
 % hmap print ./bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift_swift_hmap.hmap
MixedObjcSwift-Swift.h -> src/MixedObjcSwift-Swift.h
MixedObjcSwift/MixedObjcSwift-Swift.h -> src/MixedObjcSwift-Swift.h
% ls src/MixedObjcSwift-Swift.h
ls: src/MixedObjcSwift-Swift.h: No such file or directory
% find . -name MixedObjcSwift-Swift.h
./bazel-out/apl-darwin_x86_64-fastbuild/bin/src/MixedObjcSwift-Swift.h
```

What I think needs to happen is that we need to get the path to the generated header from the `generated_header_name` attribute of the `SwiftInfo` provider and make that the value in the header map.
